### ISSUE TITLE
Allow whitelisting Kubernetes clusters

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/mint-storage#40]
To better support the Kubernetes OAuth/IAM integration (see slide 21+ of https://www.slideshare.net/try_except_/large-scale-kubernetes-on-aws-at-europes-leading-online-fashion-platform-container-days-hamburg), we need to allow whitelisting individual Kubernetes clusters in STUPS' mint infrastructure.

We therefore need to add a list of Kubernetes cluster IDs (array of strings) to the application object to both the API and database, similar to the existing `s3_buckets` field:

```
        kubernetes_clusters:
                type: array
                description: |
                  Kubernetes cluster ID to allow credentials to provisioned to for this application.
                items:
                  type: string
                  example: "aws:123123123123:eu-central-1:foobar"
```

The property can be empty (backwards compatible) and should have the same read/write semantics as the existing `s3_buckets` field.

Terminology:

  * STUPS-compatible token: token with `uid` set to `stups_<application>`, used in STUPS infrastructure
  * Kubernetes token: token with `uid` set to `credprov-...`, used in Kubernetes infrastructure

Acceptance criteria:

 - [ ] Mint-storage has an API for storing a list of Kubernetes clusters (list of cluster IDs, no wildcards or regex matching)
 - The following use cases are supported:
   * [ ] Applications with neither S3 buckets nor Kubernetes clusters configured (only Kubernetes tokens can be generated)
   * [ ] Applications with at least one S3 bucket and no Kubernetes clusters (STUPS-compatible tokens and Kubernetes tokens can be generated)
   * [ ] Applications with Kubernetes clusters configured (Kubernetes tokens can be generated in all clusters; STUPS-compatible tokens can be generated in whitelisted clusters)
 - [ ] Existing use cases continue to be supported
 - [ ] Tests are written for this feature
 - [ ] New version is deployed
